Developer-DAO/web3-ui

_templates/component/with-prompt/reactComponent.ejs.t, _templates/component/with-prompt/reactComponentStory.ejs.t, _templates/component/with-prompt/reactComponentStyle.ejs.t
Changed the output of the `yarn component:new` script.
Now, the script won't create `.scss` files and the storybook files are now correctly importing the component.
=> ci: fix `yarn component:new` script

.husky/pre-commit, package.json, yarn.lock
Initially while committing, a pre-commit hook was formatting the unformatted files, but the formatted file(s) was not getting added to the staging. To add these unstaged files to staging, one more commit was required to be done.
All the modified files which get formatted by husky get added to the staging in a single commit and no need to add another commit to add these files to staging.
**What changes I've done?**
1. Removed husky from the project.
2. Re-installed husky following the [docs](https://typicode.github.io/husky/#/)
=> Fix husky issue

.husky/pre-commit, package.json, yarn.lock
This short PR introduces the usage of `lint-staged` in the husky pre-commit hook.
TIL that Husky actually changed their approach to their Javascript configuration in v7.
Instead of it being done through `package.json` or an `.huskyrc.json`, it's now done with a bash script file within the `.husky` folder.
They explain the reasoning here:
https://blog.typicode.com/husky-git-hooks-javascript-config/
You can see the migration docs too:
https://typicode.github.io/husky/#/?id=migrate-from-v4-to-v7
=> chore: use husky with lint staged

packages/components/src/components/Address/Address.stories.tsx, packages/hooks/src/hooks/useWallet.ts, yarn.lock
While verifying other changes, i noticed that the Address with wallet story wasn't working. that was because the provider was added after the `useWallet` hook. I fixed that, a type in the useWallet hook docstring, and ran `yarn install`
screenshots:
renders the modal
shows the address on the testnet
on mainnet shows my ENS address
to: @Dhaiwat10
=> Fix story for address with wallet

CONTRIBUTING.md
This is to keep the [CONTRIBUTING.md](https://github.com/Developer-DAO/web3-ui/blob/master/CONTRIBUTING.md) file up to date, removing the reference to `yarn dev` which no longer exists.
=> Remove reference to `yarn dev` in CONTRIBUTING.md

.github/ISSUE_TEMPLATE/feature.yml, .github/pull_request_template.md
While going through the issues in this repo, I realised one of the PRs had not been linked to an issue, which in turn made me realise we don't have a standard template for adding PRs or issues. 
Templates introduce a bit more consistency in general.
I tried to keep it simple and to the point.
I took inspiration from Chakra's templates and modified them to our use case.
=> chore: add GitHub templates

CONTRIBUTING.md, README.md
After adding chromatic, we should be opening PRs off of branches within the repo, that way the ci checks work
=> Update docs to recommend cloning instead of forking

.storybook/preview.js
Set the `Docs` tab as a default view mode for stories in Storybook.
⚠️ You might notice that the initial render of the Storybook has the `Canvas` tab open and only after clicking on a different story it would start defaulting to `Docs`. I've checked with my other Storybook projects that use this addon - same behaviour. 
Suboptimal, but quite minor tbf
=> set Storybook default viewmode to "Docs"

CONTRIBUTING.md, CONTRIBUTING_ON_WINDOWS.md, README.md
Add new readme for developing on Windows.
=> add readme for windows development

.changeset/heavy-ladybugs-marry.md, .gitignore, packages/components/package.json, packages/core/package.json, packages/hooks/package.json
Closes #87
This copies over the `README` and `LICENSE` from the root to the package before we publish to npm. Personally in the future I'd go for `README` files for each package that contain minimal information as to how the package works, how to install it and the version/test-coverage/...
=> (chore) - add readme and license to published package

.changeset/gold-phones-unite.md, packages/components/.babelrc, packages/components/package.json, packages/core/.babelrc, packages/core/package.json, packages/hooks/.babelrc, packages/hooks/package.json
Closes #115
preconstruct doesn't automatically include `regeneratorRuntime` this fixes that crash
=> include regenerator runtime babel runtime vars

.changeset/long-buses-brush.md, packages/hooks/src/Provider.tsx, packages/hooks/src/hooks/useWallet.ts, packages/hooks/src/stories/ConnectWallet.stories.tsx
Closes #119 
This PR adds a method `switchToCorrectNetwork` to the `useWallet()` hook. This method allows the user to connect to the required network without manually heading over to the MetaMask and switching the network.
Users can use this method by directly assigning this `switchToCorrectNetwork` function to the `onClick` handler of any button and then the magic will happen and the MetaMask network will get changed to the required network.
In case, any user doesn't have MetaMask installed then it will show an alert to the user and ask them to install MetaMask.
=> Add `switchToCorrectNetwork` method

.changeset/tiny-teachers-taste.md, packages/components/src/components/Address/Address.test.tsx, packages/components/src/components/Address/Address.tsx
Closes #124 
Updated the Address component to use `Text` ChakraUI component instead of unnecessary `Input` component.
It currently doesn't have any styling. It's up to the user to wrap it inside a styled container. I reckon let's wait until we have a design system before making a styled version of Address component?
=> Address should not use input element

packages/components/src/components/NFTGallery/NFTGallery.stories.tsx
Closes #127 
While i don't think we can guarantee window.ethereum is provided, we can at least only disable screenshotting on the one bad story
follows docs here: https://www.chromatic.com/docs/ignoring-elements#ignore-stories
to: @Dhaiwat10
=> Only disable chromatic on a single story

.changeset/eighty-icons-grab.md, packages/components/src/components/NFT/NFT.stories.tsx, packages/components/src/components/NFT/NFT.tsx, packages/components/src/components/NFTGallery/NFTGallery.stories.tsx, packages/components/src/components/NFTGallery/NFTGallery.tsx
Closes #94 
Attempts to ensure all nft cards are squares of the same size. Also adds some more docs
to: @Dhaiwat10
=> Fix NFT sizes and add docs

.changeset/fresh-camels-pay.md, packages/hooks/src/hooks/index.ts, packages/hooks/src/hooks/useTransaction.ts, packages/hooks/src/stories/UseTransaction.stories.tsx
Closes #126 
I've added a `useTransaction` hook. This hook takes the **function** and an array of **arguments** to this function as an argument. 
This hook returns an object containing the `execute` method, `loading` state, and `error` state. On calling this `execute` method, the function passed in the hook as an argument will get executed.
=> Add `useTransaction` hook

.changeset/lemon-donkeys-battle.md, packages/hooks/src/hooks/useTransaction.ts, packages/hooks/src/stories/UseTransaction.stories.tsx
- The `useTransaction` hook wasn't waiting for the transaction to be confirmed before setting `loading` as `false`.
- I have also re-factored the story for the hook to use `Form` elements.
- Updated the docstrings.
=> Fix `loading` state of `useTransaction` and refactor story

.changeset/few-queens-bathe.md, package.json, packages/components/package.json, packages/components/src/components/NFT/NFT.tsx, packages/components/src/components/NFTGallery/NFTGallery.tsx, packages/core/package.json, utils/setupTests.ts, yarn.lock
Closes #145
Closes #128
This removes the extraneous `@emotion/core`, `cross-fetch` and `classnames` deps
=> (chore) - remove extraneous deps

.changeset/tiny-bees-film.md, packages/components/src/components/Provider/Provider.tsx
Closes #137
Spread built in ChakraProviderProps to Provider Component.
=> Spread ChakraProvider props to Provider Component

.changeset/yellow-eyes-eat.md, packages/components/src/components/Address/Address.tsx
Closes #151 
Added a null check for the "value" prop to resolve "Cannot read properties of null" error.
=> added null check for value prop

.changeset/lovely-cars-thank.md, .gitignore, packages/components/README.md, packages/components/package.json, packages/components/src/components/TokenGate/TokenGate.tsx, packages/core/README.md, packages/core/package.json, packages/hooks/README.md, packages/hooks/package.json
- Tweaked the `prePublish` scripts to not copy over the README from the root directory. The build should use the READMEs located in the individual package folders now.
- Added a README for the components package.
=> Add setup for individual READMEs and add README content for components

package.json, packages/hooks/src/hooks/useWallet.test.tsx, yarn.lock
Closes #176 
Add @testing-library/react-hooks, make use of Provider for context and test that useWallet can instantiate and trigger the request to connect to the correct network.
Pretty basic tests, but extensible if we want to either deeply mock window.ethereum, make use of another external library (though none jump out as best-choice), or solve this in another way.
=> Create test for useWallet

.changeset/rare-days-punch.md, packages/hooks/src/hooks/useContract.ts
This PR introduces a new check in the `useContract` hook which only attempts to initalize the contract if the user has connected their wallet. Calling contracts when the user hadn't connected their wallet was throwing errors.
=> Add check for `context.connected` in `useContract` for readiness

.changeset/metal-guests-flash.md, packages/hooks/README.md, packages/hooks/src/Provider.tsx, packages/hooks/src/hooks/index.ts, packages/hooks/src/hooks/useReadOnlyContract.ts, packages/hooks/src/hooks/useReadOnlyProvider.ts, packages/hooks/src/hooks/useStaticProvider.ts, packages/hooks/src/hooks/useWallet.ts, packages/hooks/src/index.ts, packages/hooks/src/stories/UseContract.stories.tsx
Closes #202 
This PR introduces the following two hooks:
- `useReadOnlyProvider` gives you a static RPC provider which you can use to read from the blockchain.
- `useReadOnlyContract`: lets you interact with a smart contract without needing a signer. (you _need_ a signer in order to use `useContract`)
Also added a new prop `rpcUrl` to the `Provider` to accept a RPC URL for the `readOnlyProvider`.
=> Add `useReadOnlyContract` and `useStaticProvider`

.changeset/clean-lobsters-kiss.md, packages/core/README.md, packages/core/package.json, packages/core/src/components/Provider/Provider.tsx, packages/core/src/components/TokenGate/TokenGate.stories.tsx, packages/core/src/components/TokenGate/TokenGate.tsx, packages/core/src/components/TokenGate/index.ts, packages/core/src/components/index.ts, packages/hooks/src/stories/UseContract.stories.tsx
This PR adds the `TokenGate` component to the `core` package.
- The `core` version of the `TokenGate` builds on top of its counterpart in `components`.
- Added `ethers` to peer dependencies of the `core` package.
=> Add `TokenGate` to `core`

packages/components/package.json, packages/core/package.json, packages/hooks/package.json
Added a `files` key to each package's `package.json` so that only the `dist` folder (and `package.json`, which is always published) is published to `npm`. 
Currently we're publishing all files in each package's directory which is unnecessary.
=> chore: publish only dist folders

babel.config.js, package.json, packages/components/.babelrc, packages/components/package.json, packages/core/.babelrc, packages/core/package.json, packages/hooks/.babelrc, packages/hooks/package.json, tsconfig.json, yarn.lock
This PR makes a number of changes to the repo in order to consolidate and clean up the build process. There's a lot of unnecessary stuff in the repo that doesn't need to exist in order for `preconstruct` to build the packages, so I removed a lot of it.
Here's a list:
- replaced individual package `.babelrc` files with a root `babel.config.js` file
- removed unused `example/package-lock.json` file
- consolidated the various `build` scripts into a single root-level `build` script
- switched to `dependencies` instead of `devDependencies` (not a required change by any means, but in the root monorepo `package.json`, there's no distinction between deps and devDevs)
- removed some `babel` dependencies that aren't required
- removed the `outDir` config from `tsconfig.json` which was breaking …
=> chore: clean up build

.changeset/tidy-goats-rule.md, packages/hooks/README.md, packages/hooks/src/hooks/useTransaction.ts, packages/hooks/src/stories/UseTransaction.stories.tsx
Closes #174 
This PR changes the API of the `useTransaction` hook. You can now pass in fn args directly to the `execute` function instead of passing them to the `useTransaction` hook.
Old API: 
```tsx
const [execute, loading, error] = useTransaction(greeter.setGreeting, ['Hello, world!',
{
value: ethers.utils.parseEther('0.1')
]);
await execute();
```
New API:
```tsx
const [execute, loading, error] = useTransaction(greeter.setGreeting);
await execute(['Hello, world!',
{
value: ethers.utils.parseEther('0.1')
}
]);
```
=> Refactor `useTransaction` hook's `execute` fn's API

.changeset/moody-kangaroos-melt.md, packages/core/src/components/TokenGate/TokenGate.tsx, packages/hooks/src/index.ts
This PR resolves a runtime error caused by an incorrect import in `TokenGate.tsx`.
Using `@web3-ui/core` caused the following error:
```
Error: Cannot find module '@web3-ui/hooks/src/constants'
```
I believe this is due to the fact that `TokenGate.tsx` was importing `ERC20ABI` using `@web3-ui/hooks/src/constants` which doesn't exist in the final build.
To resolve this, I added `ERC20ABI` as an export from `@web3-ui/hooks` and updated the imports in `TokenGate.tsx`.
=> fix(hooks): add ERC20ABI, ERC721ABI exports

README.md, example/.gitignore, example/abis/Greeter.json, example/package.json, example/pages/index.tsx, packages/hooks/README.md, packages/hooks/src/hooks/useContract.ts, yarn.lock
Closes #197 
Allows to auto-generate TypeScript smart contract type definitions based on the ABIs provided by the user.
Though it can't be generated in runtime but will have to let user do additional step to generate these typings. We can explore some other ideas if anyone has a better approach to this, the way I see how the developer would be generating types is to execute a command from `typechain`, which should be additional dependency for their side... 
1. Given that they only installed this hooks package, and `useContract` is already being imported and used
2. Install `typechain` library by `yarn add typechain --dev` or `npm i -D typechain`
3. Add a script into their `package.json` file, the script can be named anything they prefer but recommend "typechain"
```json
"scripts": { …
```
=> Add generic type argument for useContract

.changeset/twelve-tables-sleep.md, packages/components/src/components/NFTGallery/NFTGallery.test.tsx, packages/components/src/components/NFTGallery/NFTGallery.tsx
The unnecessary static heading at the top of the NFTGallery component has been removed.
=> Remove unnecessary text from the top of `NFTGallery`

.changeset/sharp-pianos-perform.md, packages/components/src/components/Address/Address.tsx
Closes #200 
>Added ENS lookup functionality directly to the address component. Previously it would only check if an ENS name was already provided
This current solution requires an RPC and uses `provider.ensLookup()` from ethers to lookup the address. While researching how to implement this properly for looking up multiple addresses i came across this link to a `reverseRecords` [contract](https://github.com/ensdomains/reverse-records) in the [ENS domain docs](https://docs.ens.domains/dapp-developer-guide/resolving-names)
```
const namehash = require('eth-ens-namehash');
const allnames = await ReverseRecords.getNames(['0x123','0x124'])
const validNames = allnames.filter((n) => namehash.normalize(n) === n )
```
So while this is a working solution, my question is should we implement it as …
=> added ens lookup to address component. Requires RPC URL.

.changeset/gold-crabs-begin.md, packages/components/src/components/Address/Address.stories.tsx, packages/components/src/components/Address/Address.tsx
Closes #211 
Removed the need for an RPC URL
> Switched the need for RPC url by using window.ethereum instead
This allows for the optional lookup of ENS names using a provider. It is optional because developers don't need to lookup ENS names in the component if they provide `connection.ens` and this lookup should not be used for looking up a high number of ENS names.
> For looking up many ENS names a contract called [reverseRecords](https://github.com/ensdomains/reverse-records) should be used and the names then provided to the address component.
=> removed RPC, made ENS lookup optional

packages/components/README.md, packages/hooks/README.md
FIx uses of the `Provider` component in readmes
`<Provider>...` becomes `<Provider network={NETWORKS.mainnet}>`
=> Documentation - Update  examples to use <Provider> correctly

.changeset/tidy-dancers-draw.md, packages/components/README.md, packages/components/src/components/NFT/NFT.stories.tsx, packages/components/src/components/NFT/NFT.tsx, packages/components/src/components/NFTGallery/NFTGallery.stories.tsx, packages/components/src/components/NFTGallery/NFTGallery.tsx
Closes #243 
- Added a new prop `isTestnet` to `NFT` and `NFTGallery`. If `isTestnet` is `true`, the NFT data will be fetched from the testnet opensea API instead of mainnet. Only Rinkeby is supported for now.
=> Add testnet support to NFT and NFTGallery

examples/vitejs/package.json
Closes #278
This PR prevents `examples/vitejs` from being included in `publish:npm` by setting `"private": true` in its `package.json`.
=> fix: make vitejs example package private

.github/workflows/ci.yaml
=> Fix checks for prs from forked repositories

.changeset/curvy-news-juggle.md, packages/components/README.md, packages/core/src/components/Provider/Provider.tsx, packages/hooks/README.md, packages/hooks/src/Provider.tsx
This pr simply relaxes the type constraint for the network prop on the `Provider` component.
Although the type currently says that it is a required prop it is not in actually and simply a different but valid configuration of this component. 
Rendering a provider like this `<Provider></Provider>` results in having the network inferred from the wallet, which is afaik a totally valid use-case.
=> Relax network attribute for Provider component

.changeset/metal-pets-remain.md, packages/hooks/src/Provider.tsx, packages/hooks/src/hooks/useWallet.ts
Closes #277 
- This handles exceptions thrown in `connectWallet` and exposes them as a provider value, and again as a value returned by `useWallet`
- As I was making this update I also made use of destructuring react imports - as it seems like good practice and seems to be consistent with the rest of the codebase.
Here's a little loom for convenience, explaining this in a bit more detail :pray:
https://www.loom.com/share/bc25f2154356452789bcaa6354f80fde?from_recorder=1&focus_title=1
=> fix: Handle connection error and expose in useWallet

.changeset/khaki-cobras-laugh.md, README.md, packages/components/README.md, packages/components/package.json, packages/core/package.json, packages/hooks/README.md, packages/hooks/package.json
Closes #220 
This PR moves `ethers` to the peer dependencies for the `components` and `hooks` package.
This means that anyone who uses our packages will now also have to manually install `ethers` alongside our packages.
Why? Mainly to avoid dependency conflicts in cases when people already have `ethers` installed.
=> Move `ethers` to peer dependencies

.github/workflows/ci.yaml
The variable for the Chromatic deployment was incorrectly named.
=> Fix incorrectly named Chromatic token var name

.changeset/curvy-phones-agree.md, packages/hooks/src/Provider.tsx
Closes #273 
removed chainId formatting from `chainChanged` event. 
before -> chainId `0x89` would be saved as `89`.
after -> chainId `0x89` will be saved as `137`
=> fix: save chainId on chainChanged event without formatting

.changeset/spicy-zoos-drive.md, packages/components/src/components/AddressInput/AddressInput.tsx, packages/hooks/src/Provider.tsx, packages/hooks/src/hooks/useTransaction.ts, packages/hooks/src/hooks/useWallet.ts
Closes #313 
Hey guys, dev #5843 here 🙌
I'm preparing a blogpost using [OpenZeppelin Defender](defender.openzeppelin.com) (which is where I work), and I decided to use Developer DAO's `web3-ui` package as my selected tool. Everything is pretty much done but I can't publish the article without publishing the build version of the project, and I need it to build with Next.js
I just changed what's causing type issues during the build, keeping every functionality untouched
I've linked the local web3-ui package to my Next.js project and still doesn't compile but it passes the type checking (seems like this is more of a Next.js specific config to support `.ts` outside of the project), so it might me cool to export JS compiled files in another PR.
If I find a workaround for this I'll update the …
=> Fix: Next.js build

.changeset/two-hotels-argue.md, packages/components/src/components/Address/Address.css, packages/components/src/components/Address/Address.tsx, packages/components/src/components/AddressInput/AddressInput.css, packages/components/src/components/AddressInput/AddressInput.tsx
This PR refactors the `Address` and `AddressInput` component. 
They now don't make use of ChakraUI. They instead use plain CSS.
=> Refactor components to drop ChakraUI

.changeset/fuzzy-countries-sniff.md, packages/components/src/components/Address/Address.tsx, packages/components/src/components/AddressInput/AddressInput.tsx
Closes #343 
This PR makes sure we are not rendering `Error` objects. We will now stringify them instead.
=> fix: Stringify errors before rendering them

.changeset/strange-carrots-wonder.md, packages/hooks/src/Provider.tsx, packages/hooks/src/stories/UseContract.stories.tsx
See stories/useWriteContract for example.
Closes #310
This exposes cacheProvider as a prop to  `<Provider />` to allow persistence with Web3Modal.
I'd like to implement some tests for this but wasn't sure how to mock accounts and didn't see any setup for that. Any ideas or examples on the best pattern to do that?
=> [hooks] Add `cacheProvider` prop to `<Provider />`

.changeset/big-ladybugs-yawn.md, packages/core/src/components/index.ts
Closes #326 
Add missing exports on core/components/index.ts for the NetworkSwitch and TokenBalance components
=> Fix: Export missing core components from root components

apps/playground/pages/web3-components/index.tsx, packages/components/src/components/TokenBalance/TokenBalance.stories.tsx, packages/components/src/components/TokenBalance/TokenBalance.test.tsx, packages/components/src/components/TokenBalance/TokenBalance.tsx, packages/components/src/components/TokenBalance/index.ts, packages/components/src/components/index.ts
Closes #366
- add component / test / storybook
- add examples to the playground
- add connect button for testing
It follows the same props as **wagmi's** `useBalance` hook with one difference: `addressOrName` is optional, and if it is skipped - we will try to take `address` from connected account
1) ![image](https://user-images.githubusercontent.com/10981565/182609179-cfa1e222-77ac-488f-b547-250466b854af.png)
2) ![image](https://user-images.githubusercontent.com/10981565/182609146-4503f61c-0c5d-4d0b-9cc5-8e9406d129b5.png)
3) ![image](https://user-images.githubusercontent.com/10981565/182609118-3d46dc64-9a29-4a0e-a9d4-2cd8c9f77c7c.png)
1) ![image](https://user-images.githubusercontent.com/10981565/182609284-87e085f1-a523-48a5-ac8d-58b21cd86dcf.png)
2) …
=> :sparkles: [issue-366] Add TokenBalance component

apps/playground/pages/web3-elements/index.tsx, packages/components/src/elements/Badge/Badge.stories.tsx, packages/components/src/elements/Button/Button.stories.tsx, packages/components/src/elements/Checkbox/Checkbox.stories.tsx, packages/components/src/elements/TextField/TextField.stories.tsx, packages/components/src/elements/TextField/TextField.test.tsx, packages/components/src/elements/TextField/TextField.tsx, packages/components/src/elements/TextField/index.ts, packages/components/src/elements/index.ts
References #354
> Adding the TextField component
=> feat:TextField

packages/components/src/elements/Dialog/Dialog.stories.tsx, packages/components/src/elements/Dialog/Dialog.test.tsx, packages/components/src/elements/Dialog/Dialog.tsx, packages/components/src/elements/Dialog/index.ts
Closes #354 
Added Dialog/Modal
=> feat: Dialog/modal
