Developer-DAO/web3-ui

packages/components/package.json
packages/hooks/package.json

This should fix the issue @Dhaiwat10 was having with using types from the hooks package in components (and vice versa).
to: @with-heart @crondinini @Dhaiwat10

Fix types from packages

---

.storybook/main.js
packages/components/src/components/Address/Address.stories.tsx
packages/components/src/components/Address/Address.tsx
packages/components/src/components/NFT/NFT.stories.tsx
packages/components/src/components/NFT/NFT.tsx
packages/components/src/components/NFTGallery/NFTGallery.stories.tsx
packages/components/src/components/NFTGallery/NFTGallery.tsx
packages/hooks/src/stories/ConnectWallet.stories.tsx

Closes #70
Configures storybook to pull in docstrings from our components. I figure that once we can get the storybook deployed to a website, this should be sufficient for people to use our components.
Still todo: figure out how to document hooks
Example:
to: @Dhaiwat10 @crondinini

Add docs in storybook

---

packages/hooks/package.json
packages/hooks/src/Provider.tsx
packages/hooks/src/stories/ConnectWallet.stories.tsx
yarn.lock

Closes #75
- I've added Coinbase and Ledger wallet Providers in useWallet hook.
- While connecting using *WalletConnect*, previously it was throwing an error that RPC not specified. To fix that, I've added RPC to the *WalletConnet* provider options.
We can accept props from the user that which wallet provider they want to use. Also, we can add support to add custom wallet providers.

Feat: Add custom Web3Modal Wallet Providers

---

.changeset/spotty-elephants-tan.md
packages/components/src/components/index.ts

This PR adds some exports that were missing. (`components` package)

chore: add missing exports

---

.changeset/gentle-beers-mix.md
package.json
packages/core/package.json

Closes #107 
- Updated the `build` script to include the `core` package
- Added `components` and `hooks` as dependencies to the `core` package
- Created changeset to re-release all three packages

Fix builds

---

.changeset/neat-turkeys-sit.md
packages/hooks/package.json
packages/hooks/src/Provider.tsx
yarn.lock

Remove ledger and coinbase providers

---

packages/components/src/components/Address/Address.stories.tsx
packages/components/src/components/Address/Address.test.tsx
packages/components/src/components/Address/Address.tsx

Update the address component to address #86.
This is only handles the shortening aspect. Not the button to allow copying the address.

update Address component with shortAddress prop

---

packages/components/src/components/Address/Address.stories.tsx
packages/components/src/components/AddressInput/AddressInput.stories.tsx
packages/components/src/components/AddressInput/AddressInput.tsx
packages/hooks/src/stories/ConnectWallet.stories.tsx
packages/hooks/src/stories/UseContract.stories.tsx
packages/hooks/src/stories/UseTokenBalance.stories.tsx

This PR just modifies some text and styling in stories.

Clean up some stories

---

packages/components/.babelrc
packages/components/src/components/Address/Address.stories.tsx
packages/components/src/components/Address/Address.test.tsx
packages/components/src/components/Address/Address.tsx
packages/components/src/components/AddressInput/AddressInput.stories.tsx
packages/components/src/components/AddressInput/AddressInput.test.tsx
packages/components/src/components/AddressInput/AddressInput.tsx
packages/components/src/components/NFT/NFT.stories.tsx
packages/components/src/components/NFT/NFT.test.tsx
packages/components/src/components/NFTGallery/NFTGallery.stories.tsx
packages/components/src/components/NFTGallery/NFTGallery.test.tsx
packages/components/src/components/TokenGate/TokenGate.stories.tsx
packages/core/.babelrc
packages/core/src/components/ConnectWallet/ConnectWallet.tsx
packages/hooks/.babelrc
packages/hooks/src/hooks/useContract.ts
packages/hooks/src/hooks/useWallet.ts
packages/hooks/src/stories/ConnectWallet.stories.tsx
packages/hooks/src/stories/UseContract.stories.tsx
packages/hooks/src/stories/UseTokenBalance.stories.tsx
packages/hooks/src/stories/UseTransaction.stories.tsx

Just ran `npx prettier --write .` over the entire codebase since we recently updated our prettier config.
Closes #156

Lint entire codebase

---

.changeset/yellow-eels-hug.md
packages/components/src/components/index.ts
packages/hooks/src/hooks/index.ts
packages/hooks/src/index.ts

Add missing exports and remove unnecessary ones

---

.changeset/popular-islands-sell.md
packages/core/src/components/ConnectWallet/ConnectWallet.stories.tsx
packages/core/src/index.ts

Export hooks from the core package

---

README.md

Adds package versions to the readme

Add package versions to readme

---

.changeset/short-eggs-juggle.md
packages/hooks/src/hooks/useContract.ts
packages/hooks/src/stories/UseContract.stories.tsx
packages/hooks/src/stories/UseTransaction.stories.tsx

Closes #167 
Create status indicator `isReady` for `useContract` hook.

Create a status indicator for useContract

---

.changeset/odd-crabs-repair.md
packages/hooks/README.md

Add docs for `hooks`

---

packages/components/package.json
packages/core/package.json
packages/hooks/package.json

Add keywords to package.json

---

packages/core/README.md

Closes #173 
Add README to `core` package

[Docs] Add readme to core package

---

.changeset/grumpy-windows-retire.md
packages/hooks/README.md
packages/hooks/src/hooks/index.ts
packages/hooks/src/hooks/usePoller.ts
packages/hooks/src/index.ts
packages/hooks/src/stories/UseContract.stories.tsx

A hook that allows the calling of a function at dedicated intervals.
A simple hook that allows calling a function at set intervals. Useful for updating the UI of your Dapp.
usePoller (callbackFn, delay)

usePoller Hook

---

package.json
packages/components/package.json
packages/core/package.json
packages/hooks/package.json

Closes #225 
This PR removes the `engines` keys from our `package.json` files. This key is unnecessary for a library of hooks/components intended for usage only in the browser.

chore: remove engines from package.json files

---

.changeset/sixty-spiders-film.md
packages/components/README.md
packages/components/src/components/TokenBalance/TokenBalance.stories.tsx
packages/components/src/components/TokenBalance/TokenBalance.test.tsx
packages/components/src/components/TokenBalance/TokenBalance.tsx
packages/components/src/components/TokenBalance/index.ts
packages/components/src/components/index.ts
packages/core/README.md
packages/core/src/components/TokenBalance/TokenBalance.stories.tsx
packages/core/src/components/TokenBalance/TokenBalance.tsx
packages/core/src/components/TokenBalance/index.ts

Closes #42 
This PR adds a `TokenBalance` componet to the `core` and `component` packages. `TokenBalance` fetches and renders the balance of an ERC20 token for a given account address.

Add `TokenBalance` component

---

example/pages/index.tsx
packages/core/src/index.ts
packages/hooks/README.md
packages/hooks/src/hooks/index.ts
packages/hooks/src/hooks/useWriteContract.ts
packages/hooks/src/index.ts
packages/hooks/src/stories/UseContract.stories.tsx
packages/hooks/src/stories/UseTransaction.stories.tsx

Closes #219 
Breaking change that changes references of useContract to useWriteContract
This updates the hook `useContract` to `useWriteContract` (#219) which ensures that people that are using this hook know that it requires the user's wallet signature.
- Updated all references (README, stories, examples)

refactor: Change useContract to useWriteContract

---

packages/components/src/components/NFTGallery/NFTGallery.tsx
yarn.lock

Closes #246 
Reset the error message

Fix(NFTGallery): reset error message

---

README.md

when playing with web3-ui, stuck with "NETWORK" in the readme.

add NETWORK

---

packages/components/src/components/TokenGate/TokenGate.stories.tsx

Fixed typo.
```
occured -> occurred
```

chore: fix typo in TokenGate.stories.tsx

---

.changeset/strong-suns-sort.md
packages/hooks/README.md
packages/hooks/src/hooks/useTransaction.ts
packages/hooks/src/stories/UseTransaction.stories.tsx

Closes #261 
> Update `execute` method from `useTransaction` to receive any arguments.
> We should call `execute` as we were calling the original method instead of an array as first argument.

feature: Receive any argumentss on execute method from useTransaction

---

.changeset/nice-nails-collect.md

Closes #288 
This PR adds a changeset for the change made in #249 which will allow a new version of `@web3-ui/hooks` to be published.

chore: add changeset

---

.changeset/four-apes-mix.md
packages/hooks/src/hooks/useWallet.ts

Closes #259 
Display alert if the user doesn't have the required network installed.
In the future, we can integrate adding the required network to the user's metamask.

Add alert if network is not added in metamask

---

packages/hooks/src/stories/UseTokenBalance.stories.tsx

Fixed typo.
```
occured -> occurred
```

chore: fix typo in UseTokenBalance.stories.tsx

---

.changeset/purple-hats-battle.md
packages/components/src/components/MultiAddressInput/MultiAddressInput.stories.tsx
packages/components/src/components/MultiAddressInput/MultiAddressInput.tsx
packages/components/src/components/MultiAddressInput/index.ts
packages/components/src/components/index.ts

This PR adds a new component called `MultiAddressInput`. Will add more docs soon.

Add basic version of MultiAddressInput

---

README.md
packages/hooks/README.md

Add deprecation notice for hooks

---

packages/components/src/components/NFTGallery/NFTGallery.tsx

Fixed typo

---

.github/workflows/release.yaml
package.json

This PR updates our `release` workflow to actually release packages whenever a "Version Packages" PR generated by `changesets` is merged.

enable automated package release

---

CONTRIBUTING.md
README.md
contributing/CONTRIBUTING_ON_WINDOWS.md
contributing/ROADMAP.md
playground/pages/index.tsx

improved readme and contributors guild

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/feature.yml

add bug template

---

packages/components/src/elements/Badge/Badge.stories.tsx
packages/components/src/elements/Badge/Badge.test.tsx
packages/components/src/elements/Badge/Badge.tsx
packages/components/src/elements/Badge/index.ts
packages/components/src/elements/index.ts
playground/pages/web3-elements/index.tsx

References #354 
> Badge element with various color variants

feature: badge-element

---

packages/components/src/common/Box.tsx
packages/components/src/common/Container.tsx
packages/components/src/common/Flex.tsx
packages/components/src/common/Grid.tsx
packages/components/src/common/Text.tsx
packages/components/src/elements/Button/Button.tsx
packages/components/src/theme/baseTheme.ts
packages/components/src/theme/darkTheme.ts
packages/components/src/theme/stitches.config.ts
playground/components/Header.tsx
playground/components/definitions/BorderRadius.tsx
playground/components/definitions/ColorPalette.tsx
playground/components/definitions/FontSize.tsx
playground/components/definitions/FontWeight.tsx
playground/pages/_app.tsx
playground/pages/global.css
playground/pages/index.tsx
playground/pages/web3-components/index.tsx
playground/pages/web3-elements/index.tsx

working dark theme

---

packages/components/src/elements/Badge/Badge.tsx
packages/components/src/theme/darkTheme.ts
packages/components/src/theme/defaultColors.ts
playground/pages/web3-elements/index.tsx

Fixes problem with background not toggling dark mode

playground bg dark mode

---

.gitignore
packages/components/package.json
packages/components/src/elements/Checkbox/Checkbox.stories.tsx
packages/components/src/elements/Checkbox/Checkbox.test.tsx
packages/components/src/elements/Checkbox/Checkbox.tsx
packages/components/src/elements/Checkbox/index.ts
packages/components/src/elements/index.ts
playground/pages/web3-elements/index.tsx
yarn.lock

References #354
- add element / storybook / test
- add an example to the playground

Feature: Checkbox

---

packages/components/package.json
packages/components/src/common/Menu.tsx
packages/components/src/common/Panel.tsx
packages/components/src/common/index.ts
packages/components/src/elements/DropdownMenu/DropdownMenu.stories.tsx
packages/components/src/elements/DropdownMenu/DropdownMenu.test.tsx
packages/components/src/elements/DropdownMenu/DropdownMenu.tsx
packages/components/src/elements/DropdownMenu/index.ts
packages/components/src/elements/README.md
packages/components/src/elements/index.ts
playground/pages/web3-elements/index.tsx
yarn.lock

References #354 
- add DropdownMenu with basic test and story
- add common Menu, Panel
- add an example to the playground
- add README.md inside elements to describe where the base of elements

feature: add DropdownMenu

---

package.json

Closes #369 
Problem when deploying docs ui site
may be errors, testing to find issue

test fixing docs build

---

apps/playground/pages/web3-elements/index.tsx
packages/components/src/elements/Avatar/Avatar.stories.tsx
packages/components/src/elements/Avatar/Avatar.test.tsx
packages/components/src/elements/Avatar/Avatar.tsx
packages/components/src/elements/Avatar/index.ts
packages/components/src/elements/index.ts

feat: avatar element

---

apps/docs/components/layout/AppHeader.tsx
apps/docs/components/layout/AppLayout.tsx
apps/docs/components/layout/SideNavigation.tsx
apps/docs/components/layout/index.ts
apps/docs/components/snippets/getting-started/index.ts
apps/docs/components/snippets/getting-started/install.ts
apps/docs/components/snippets/getting-started/package.ts
apps/docs/components/snippets/getting-started/provider.ts
apps/docs/components/snippets/getting-started/theme.ts
apps/docs/package.json
apps/docs/pages/_app.tsx
apps/docs/pages/getting-started/index.tsx
apps/docs/pages/index.tsx
apps/docs/postcss.config.js
apps/docs/styles/globals.css
apps/docs/tailwind.config.js
yarn.lock

feat:basic docs setup

---

apps/docs/components/layout/AppHeader.tsx
apps/docs/components/layout/AppLayout.tsx
apps/docs/components/layout/SideNavigation.tsx
apps/docs/package.json
apps/docs/pages/getting-started/index.tsx
apps/docs/pages/theme/customize-theme.tsx
apps/docs/pages/theme/dark-mode.tsx
apps/docs/pages/theme/default-theme.tsx
yarn.lock

> Improved navigation for docs

improved docs navigation

---

.gitignore
apps/docs/components/layout/SideNavigation.tsx
apps/docs/package.json
apps/docs/pages/_app.tsx
apps/docs/pages/components/address-component.tsx
apps/docs/pages/components/nft-component.tsx
apps/docs/pages/components/token-component.tsx
apps/docs/pages/hooks/alchemy-hooks.tsx
apps/docs/pages/hooks/ankr-hooks.tsx
apps/playground/pages/_app.tsx
apps/playground/pages/web3-components/index.tsx
apps/storybook/.storybook/decorator.tsx
package.json
packages/components/package.json
packages/components/src/components/Address/Address.stories.tsx
packages/components/src/components/NFT/NFT.stories.tsx
packages/components/src/components/NFT/NFT.tsx
packages/components/src/components/TokenBalance/TokenBalance.stories.tsx
packages/components/src/components/index.ts
packages/components/src/index.tsx
packages/components/src/provider/Web3uiProvider/Web3uiProvider.tsx
packages/hooks/package.json
packages/hooks/src/hooks/index.ts
packages/hooks/src/index.ts
packages/hooks/src/provider/HooksProvider.tsx
packages/hooks/src/provider/index.ts
packages/hooks/src/utils.ts
packages/hooks/tsconfig.json
yarn.lock

> This PR adds ankr hooks to @web3-ui/hooks for fetching data from the ankr API
includes a hooks provider for including a set of alchemy hooks

feat ankr hooks

---

apps/playground/pages/web3-elements/index.tsx
packages/components/src/elements/Card/Card.stories.tsx
packages/components/src/elements/Card/Card.test.tsx
packages/components/src/elements/Card/Card.tsx
packages/components/src/elements/Card/index.ts
packages/components/src/elements/index.ts

Reference #354
> Adding basic card element with story and test

adding the card element

---

contributing/ROADMAP.md
packages/components/src/components/TokenBalance/TokenBalance.test.tsx
packages/components/src/elements/Avatar/Avatar.stories.tsx
packages/components/src/elements/Avatar/Avatar.test.tsx
packages/components/src/elements/Badge/Badge.test.tsx
packages/components/src/elements/Badge/Badge.tsx
packages/components/src/elements/Button/Button.test.tsx
packages/components/src/elements/Card/Card.test.tsx
packages/components/src/elements/Checkbox/Checkbox.test.tsx
packages/components/src/elements/DropdownMenu/DropdownMenu.test.tsx

> Removed no longer needed react imports in storybook and test files.

chore:removed no longer needed react import

---

apps/docs/package.json
apps/playground/package.json
apps/storybook/package.json
package.json
yarn.lock

> update storybook and @babel/core packages
also yarn upgrade

chore:update packages

---

apps/playground/pages/web3-components/index.tsx
packages/components/package.json
packages/components/src/components/ENSAvatar/ENSAvatar.stories.tsx
packages/components/src/components/ENSAvatar/ENSAvatar.test.tsx
packages/components/src/components/ENSAvatar/ENSAvatar.tsx
packages/components/src/components/ENSAvatar/index.ts
packages/components/src/components/index.ts
yarn.lock

Closes #383
Add a simple web3 avatar component

feat: ens-avatar component

---

apps/storybook/.storybook/main.ts
packages/components/package.json
packages/components/src/components/ENSAvatar/ENSAvatar.stories.tsx
packages/components/src/elements/Checkbox/Checkbox.stories.tsx
packages/hooks/package.json
yarn.lock

updating ankr-react library
update include a hook to query NFT metadata

chore:update ankr-react

---

packages/components/src/elements/Link/Link.stories.tsx
packages/components/src/elements/Link/Link.test.tsx
packages/components/src/elements/Link/Link.tsx
packages/components/src/elements/Link/index.ts

Reference #354 
Adding Link component

feat: link

---

apps/docs/components/snippets/hooks/ankr/index.ts
apps/docs/components/snippets/hooks/ankr/use_nft_metadata.ts
apps/docs/pages/hooks/ankr-hooks.tsx
packages/components/src/components/NFT/NFT.tsx
packages/components/src/provider/Web3uiProvider/Web3uiProvider.tsx
packages/hooks/package.json
packages/hooks/src/provider/AlchemyProvider.tsx
packages/hooks/src/provider/index.ts
yarn.lock

docs:add useNFTMetadata

---

apps/playground/pages/web3-elements/index.tsx

fixes issue in playground
this will fix the CI github action

fix:playground error from dropdown merge
